# syntax=docker/dockerfile:1.6
# Generated Dockerfile - DO NOT EDIT MANUALLY
# Generated by: scripts/generate-dockerfiles.sh
# Base: alpine-3.20
# Architecture: amd64

# Base image
FROM alpine:3.20 AS base

# Common environment variables
ENV TZ=UTC \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH="/usr/local/go/bin:/go/bin:${PATH}"

# Create non-root user
RUN addgroup -S foundry && adduser -S -G foundry -h /home/foundry -s /bin/bash foundry

# Set working directory
WORKDIR /workspace

# Change ownership
RUN chown -R foundry:foundry /workspace


# Alpine-specific base setup
RUN apk add --no-cache \
    ca-certificates \
    curl \
    wget \
    jq \
    git \
    bash


# Layer for Go installation
FROM base AS go-layer
ARG GO_VERSION=1.26.1
ARG TARGETARCH

RUN if [ -n "$GO_VERSION" ]; then \
    case "${TARGETARCH}" in \
        amd64) GO_ARCH="amd64" ;; \
        arm64) GO_ARCH="arm64" ;; \
        *) echo "Unsupported architecture: ${TARGETARCH}"; exit 1 ;; \
    esac && \
    curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz" -o /tmp/go.tar.gz && \
    tar -C /usr/local -xzf /tmp/go.tar.gz && \
    rm /tmp/go.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/local/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt; \
    fi

ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV GOBIN=$GOPATH/bin



# Layer for security tools
FROM base AS security-layer
ARG TARGETARCH


# Install Trivy (non-fatal on Alpine)
RUN set +e; \
    TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep -o '"tag_name": "v[^"]*"' | cut -d'"' -f4 | sed 's/v//' 2>/dev/null); \
    if [ -n "$TRIVY_VERSION" ]; then \
        case "${TARGETARCH}" in \
            amd64) TRIVY_ARCH="Linux-64bit" ;; \
            arm64) TRIVY_ARCH="Linux-ARM64" ;; \
            *) TRIVY_ARCH="Linux-64bit" ;; \
        esac && \
        wget -O /tmp/trivy.tar.gz "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_${TRIVY_ARCH}.tar.gz" 2>/dev/null && \
        tar -xzf /tmp/trivy.tar.gz -C /usr/local/bin/ trivy 2>/dev/null; \
        rm -f /tmp/trivy.tar.gz; \
    fi; \
    touch /usr/local/bin/trivy 2>/dev/null; \
    echo "Trivy setup complete" 

# Install Cosign
ARG COSIGN_VERSION=
RUN COSIGN_VERSION=${COSIGN_VERSION:-$(curl -s https://api.github.com/repos/sigstore/cosign/releases/latest | grep -o '"tag_name": "v[^"]*"' | cut -d'"' -f4)} && \
    case "${TARGETARCH}" in \
        amd64) COSIGN_ARCH="amd64" ;; \
        arm64) COSIGN_ARCH="arm64" ;; \
        *) COSIGN_ARCH="${TARGETARCH}" ;; \
    esac && \
    curl -fsSL -o /usr/local/bin/cosign "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-${COSIGN_ARCH}" && \
    chmod +x /usr/local/bin/cosign

# Install Syft
RUN curl -fsSL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

# Layer for compliance tools
FROM base AS compliance-layer
ARG TARGETARCH



# Install OpenSCAP for Alpine
RUN apk add --no-cache \
    openscap \
    python3 \
    py3-pip \
    wget \
    ca-certificates

# Install OpenSCAP content for Alpine (may not be available)
RUN mkdir -p /usr/share/xml/scap/ssg/content && \
    wget -O /usr/share/xml/scap/ssg/content/ssg-alpine319-xccdf.xml \
    https://github.com/ComplianceAsCode/content/releases/latest/download/ssg-alpine319-xccdf.xml || true

# Install OPA (Open Policy Agent)
RUN OPA_VERSION=$(curl -s https://api.github.com/repos/open-policy-agent/opa/releases/latest | grep -o '"tag_name": "v[^\"]*"' | cut -d'"' -f4 | sed 's/v//') && \
    wget -O /usr/local/bin/opa "https://github.com/open-policy-agent/opa/releases/download/v${OPA_VERSION}/opa_linux_${TARGETARCH}" && \
    chmod +x /usr/local/bin/opa

# Create compliance policies directory
RUN mkdir -p /opt/compliance/policies /opt/compliance/reports

# Copy compliance policies
COPY compliance/ /opt/compliance/policies/

# Layer for DevOps tools
FROM base AS devops-layer
ARG TARGETARCH


# Install Docker CLI
RUN apk add --no-cache docker-cli

# Install kubectl
RUN KUBECTL_VERSION=1.35.1 && \
    case "${TARGETARCH}" in \
        amd64) KUBECTL_ARCH="amd64" ;; \
        arm64) KUBECTL_ARCH="arm64" ;; \
        *) KUBECTL_ARCH="${TARGETARCH}" ;; \
    esac && \
    curl -fsSL -o /usr/local/bin/kubectl "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${KUBECTL_ARCH}/kubectl" && \
    chmod +x /usr/local/bin/kubectl

# Install helm
RUN HELM_VERSION=3.19.5 && \
    case "${TARGETARCH}" in \
        amd64) HELM_ARCH="amd64" ;; \
        arm64) HELM_ARCH="arm64" ;; \
        *) HELM_ARCH="${TARGETARCH}" ;; \
    esac && \
    curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${HELM_ARCH}.tar.gz" -o /tmp/helm.tar.gz && \
    tar -xzf /tmp/helm.tar.gz -C /tmp && \
    mv /tmp/linux-${HELM_ARCH}/helm /usr/local/bin/helm && \
    rm -rf /tmp/helm.tar.gz /tmp/linux-${HELM_ARCH}


# Final assembly
FROM base AS final

# Copy tools from layers if they were built
COPY --from=go-layer /usr/local/go /usr/local/go
COPY --from=go-layer /usr/local/bin/go* /usr/local/bin/


COPY --from=security-layer /usr/local/bin/trivy /usr/local/bin/trivy

COPY --from=security-layer /usr/local/bin/cosign /usr/local/bin/cosign

COPY --from=security-layer /usr/local/bin/syft /usr/local/bin/syft

COPY --from=compliance-layer /usr/local/bin/opa /usr/local/bin/opa
COPY --from=compliance-layer /opt/compliance /opt/compliance

COPY --from=devops-layer /usr/local/bin/kubectl /usr/local/bin/kubectl

COPY --from=devops-layer /usr/local/bin/helm /usr/local/bin/helm



# Additional packages from config
RUN apk add --no-cache vim

# CIS 5.1: Remove setuid/setgid binaries to reduce privilege escalation risk
RUN find / -xdev -perm /6000 -type f -exec chmod a-s {} \; 2>/dev/null || true

# CIS 5.2: Remove world-writable permissions (except expected ones)
RUN find / -xdev -type d -perm 0002 ! -path /proc/* ! -path /dev/shm/* -exec chmod o-w {} + 2>/dev/null || true

# CIS 4.6: HEALTHCHECK instruction
HEALTHCHECK NONE

# Restrictive umask for file creation
RUN echo "umask 027" >> /etc/bash.bashrc && \
    echo "umask 027" >> /etc/profile

# Disable shell command history for non-interactive use
RUN echo "HISTSIZE=0" >> /etc/bash.bashrc && \
    rm -f /root/.bash_history 2>/dev/null || true

# Clean up build artifacts and cached data
RUN rm -rf /tmp/* /var/tmp/* 2>/dev/null || true

# Labels
LABEL org.opencontainers.image.title="ImageFoundry Base Image (alpine-3.20)"
LABEL org.opencontainers.image.description="Custom-built container image with development tools"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.created="2026-05-12T23:07:27Z"
LABEL org.opencontainers.image.source="https://github.com/simonbbbb/ImageFoundry"
LABEL org.opencontainers.image.authors="ImageFoundry Team"
LABEL org.opencontainers.image.url="https://github.com/simonbbbb/ImageFoundry"
LABEL org.opencontainers.image.documentation="https://github.com/simonbbbb/ImageFoundry"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.revision="df83299"
LABEL org.opencontainers.image.base.name="alpine:3.20"
LABEL org.opencontainers.image.security.seccomp="default"
LABEL org.opencontainers.image.security.apparmor="runtime/default"

# Switch to non-root user
USER foundry

# Default command
CMD ["/bin/bash"]
