# syntax=docker/dockerfile:1.6
# Generated Dockerfile - DO NOT EDIT MANUALLY
# Generated by: scripts/generate-dockerfiles.sh
# Base: ubuntu-22.04
# Architecture: amd64

# Base image
FROM ubuntu:22.04 AS base

# Common environment variables
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH="/usr/local/go/bin:/go/bin:${PATH}"

# Create non-root user
RUN groupadd -r foundry && useradd -r -g foundry -m -s /bin/bash foundry

# Set working directory
WORKDIR /workspace

# Change ownership
RUN chown -R foundry:foundry /workspace

# Ubuntu-specific base setup
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    wget \
    gnupg \
    jq \
    git \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean



# Layer for Go installation
FROM base AS go-layer
ARG GO_VERSION=1.26.1
ARG TARGETARCH

RUN if [ -n "$GO_VERSION" ]; then \
    case "${TARGETARCH}" in \
        amd64) GO_ARCH="amd64" ;; \
        arm64) GO_ARCH="arm64" ;; \
        *) echo "Unsupported architecture: ${TARGETARCH}"; exit 1 ;; \
    esac && \
    curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz" -o /tmp/go.tar.gz && \
    tar -C /usr/local -xzf /tmp/go.tar.gz && \
    rm /tmp/go.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/local/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt; \
    fi

ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV GOBIN=$GOPATH/bin



# Layer for security tools
FROM base AS security-layer
ARG TARGETARCH

# Install Trivy
RUN curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor -o /usr/share/keyrings/trivy.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" > /etc/apt/sources.list.d/trivy.list && \
    apt-get update && apt-get install -y --no-install-recommends trivy && rm -rf /var/lib/apt/lists/*


# Install Cosign
ARG COSIGN_VERSION=
RUN COSIGN_VERSION=${COSIGN_VERSION:-$(curl -s https://api.github.com/repos/sigstore/cosign/releases/latest | grep -o '"tag_name": "v[^"]*"' | cut -d'"' -f4)} && \
    case "${TARGETARCH}" in \
        amd64) COSIGN_ARCH="amd64" ;; \
        arm64) COSIGN_ARCH="arm64" ;; \
        *) COSIGN_ARCH="${TARGETARCH}" ;; \
    esac && \
    curl -fsSL -o /usr/local/bin/cosign "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-${COSIGN_ARCH}" && \
    chmod +x /usr/local/bin/cosign

# Install Syft
RUN curl -fsSL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

# Layer for compliance tools
FROM base AS compliance-layer
ARG TARGETARCH


# Install OpenSCAP for Ubuntu 22.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    openscap-scanner \
    scap-security-guide \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Install OpenSCAP content for Ubuntu 22.04
RUN mkdir -p /usr/share/xml/scap/ssg/content && \
    wget -O /usr/share/xml/scap/ssg/content/ssg-ubuntu2204-xccdf.xml \
    https://github.com/ComplianceAsCode/content/releases/latest/download/ssg-ubuntu2204-xccdf.xml || true


# Install OPA (Open Policy Agent)
RUN OPA_VERSION=$(curl -s https://api.github.com/repos/open-policy-agent/opa/releases/latest | grep -o '"tag_name": "v[^\"]*"' | cut -d'"' -f4 | sed 's/v//') && \
    wget -O /usr/local/bin/opa "https://github.com/open-policy-agent/opa/releases/download/v${OPA_VERSION}/opa_linux_${TARGETARCH}" && \
    chmod +x /usr/local/bin/opa

# Create compliance policies directory
RUN mkdir -p /opt/compliance/policies /opt/compliance/reports

# Copy compliance policies
COPY compliance/ /opt/compliance/policies/

# Layer for DevOps tools
FROM base AS devops-layer
ARG TARGETARCH

# Install Docker CLI
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    UBUNTU_CODENAME=$(awk -F= '/^VERSION_CODENAME=/ {print $2}' /etc/os-release) && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu ${UBUNTU_CODENAME} stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && apt-get install -y --no-install-recommends docker-ce-cli && rm -rf /var/lib/apt/lists/*


# Install kubectl
RUN KUBECTL_VERSION=1.35.1 && \
    case "${TARGETARCH}" in \
        amd64) KUBECTL_ARCH="amd64" ;; \
        arm64) KUBECTL_ARCH="arm64" ;; \
        *) KUBECTL_ARCH="${TARGETARCH}" ;; \
    esac && \
    curl -fsSL -o /usr/local/bin/kubectl "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${KUBECTL_ARCH}/kubectl" && \
    chmod +x /usr/local/bin/kubectl

# Install helm
RUN HELM_VERSION=3.19.5 && \
    case "${TARGETARCH}" in \
        amd64) HELM_ARCH="amd64" ;; \
        arm64) HELM_ARCH="arm64" ;; \
        *) HELM_ARCH="${TARGETARCH}" ;; \
    esac && \
    curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${HELM_ARCH}.tar.gz" -o /tmp/helm.tar.gz && \
    tar -xzf /tmp/helm.tar.gz -C /tmp && \
    mv /tmp/linux-${HELM_ARCH}/helm /usr/local/bin/helm && \
    rm -rf /tmp/helm.tar.gz /tmp/linux-${HELM_ARCH}


# Final assembly
FROM base AS final

# Copy tools from layers if they were built
COPY --from=go-layer /usr/local/go /usr/local/go
COPY --from=go-layer /usr/local/bin/go* /usr/local/bin/


COPY --from=security-layer /usr/bin/trivy /usr/bin/trivy

COPY --from=security-layer /usr/local/bin/cosign /usr/local/bin/cosign

COPY --from=security-layer /usr/local/bin/syft /usr/local/bin/syft

COPY --from=compliance-layer /usr/local/bin/opa /usr/local/bin/opa
COPY --from=compliance-layer /opt/compliance /opt/compliance

COPY --from=devops-layer /usr/local/bin/kubectl /usr/local/bin/kubectl

COPY --from=devops-layer /usr/local/bin/helm /usr/local/bin/helm

COPY --from=devops-layer /usr/bin/docker /usr/bin/docker


# Additional packages from config
RUN apt-get update && apt-get install -y --no-install-recommends vim && rm -rf /var/lib/apt/lists/* && apt-get clean

# CIS 5.1: Remove setuid/setgid binaries to reduce privilege escalation risk
RUN find / -xdev -perm /6000 -type f -exec chmod a-s {} \; 2>/dev/null || true

# CIS 5.2: Remove world-writable permissions (except expected ones)
RUN find / -xdev -type d -perm 0002 ! -path /proc/* ! -path /dev/shm/* -exec chmod o-w {} + 2>/dev/null || true

# CIS 4.6: HEALTHCHECK instruction
HEALTHCHECK NONE

# Restrictive umask for file creation
RUN echo "umask 027" >> /etc/bash.bashrc && \
    echo "umask 027" >> /etc/profile

# Disable shell command history for non-interactive use
RUN echo "HISTSIZE=0" >> /etc/bash.bashrc && \
    rm -f /root/.bash_history 2>/dev/null || true

# Clean up build artifacts and cached data
RUN rm -rf /tmp/* /var/tmp/* 2>/dev/null || true

# Labels
LABEL org.opencontainers.image.title="ImageFoundry Base Image (ubuntu-22.04)"
LABEL org.opencontainers.image.description="Custom-built container image with development tools"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.created="2026-05-12T23:07:27Z"
LABEL org.opencontainers.image.source="https://github.com/simonbbbb/ImageFoundry"
LABEL org.opencontainers.image.authors="ImageFoundry Team"
LABEL org.opencontainers.image.url="https://github.com/simonbbbb/ImageFoundry"
LABEL org.opencontainers.image.documentation="https://github.com/simonbbbb/ImageFoundry"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.revision="df83299"
LABEL org.opencontainers.image.base.name="ubuntu:22.04"
LABEL org.opencontainers.image.security.seccomp="default"
LABEL org.opencontainers.image.security.apparmor="runtime/default"

# Switch to non-root user
USER foundry

# Default command
CMD ["/bin/bash"]
