#!/bin/bash

set -euo pipefail

# Function to create issue if version is outdated
create_issue() {
  local tool=$1
  local current=$2
  local latest=$3
  local repo=$4
  
  if [ "$current" != "$latest" ]; then
    echo "Update available for $tool: $current -> $latest"
    
    # Check if issue already exists
    existing_issue=$(gh issue list --repo "$repo" --label "version-update,$tool" --state open --json number --jq '.[0].number // empty')
    
    if [ -z "$existing_issue" ]; then
      echo "Creating issue for $tool update"
      
      # Create issue body as a temporary file
      cat > /tmp/issue_body.md << EOF
## 📦 Tool Update Available

**Tool:** $tool  
**Current Version:** $current  
**Latest Version:** $latest  

### 🎯 Action Required
Update the version in \`configs/image-foundry.yaml\`:

\`\`\`yaml
tools:
  languages:
    $tool:
      version: "$latest"
\`\`\`

### 📋 Checklist
- [ ] Update version in config file
- [ ] Test build with new version
- [ ] Update any documentation if needed
- [ ] Consider updating related dependencies

### 🤖 Generated by
This issue was automatically created by the version-check workflow.

---
**Note:** This is a low-priority enhancement. Update when convenient.
EOF
      
      gh issue create \
        --title "🔄 Update $tool from $current to $latest" \
        --label "version-update,$tool,enhancement" \
        --body-file /tmp/issue_body.md \
        --repo "$repo"
        
      rm /tmp/issue_body.md
    else
      echo "Issue for $tool update already exists (#$existing_issue)"
    fi
  else
    echo "$tool is up to date ($current)"
  fi
}

# Parse arguments
tool=$1
current=$2
latest=$3
repo=$4

# Create issue if needed
create_issue "$tool" "$current" "$latest" "$repo"
